#!/bin/bash

# Run on client:
echo "Enter 'yes' (no quotes) if you are asked to continue connecting."
echo "Enter 'dees' (no quotes) for the next password."
echo "Use ctrl-c to exit."
ssh -w 0:0 root@192.168.20.99 \
    -o "PermitLocalCommand=yes" \
    -o "LocalCommand= ip addr add 192.168.53.88/24 dev tun0 && \
                      ip link set tun0 up" \
    -o "RemoteCommand=ip addr add 192.168.53.99/24 dev tun0 && \
                      ip link set tun0 up"
exit


# Run on client in separate window:
ip route replace 192.168.20.0/24 dev tun0
ip route add 192.168.20.99 via 10.8.0.11


# Run on server:
iptables -t nat -A POSTROUTING -j MASQUERADE -o eth0
