#!/bin/bash

echo "Enter 'yes' (no quotes) if you are asked to continue connecting."
echo "Enter 'dees' (no quotes) for the next password."
ssh -w 0:0 root@192.168.20.99 \
    -o "PermitLocalCommand=yes" \
    -o "LocalCommand= ip addr add 192.168.53.88/24 dev tun0 && \
                      ip link set tun0 up" \
    -o "RemoteCommand=ip addr add 192.168.53.99/24 dev tun0 && \
                      ip link set tun0 up"

ip route replace 192.168.20.0/24 dev tun0
ip route add 192.168.20.99 via 10.8.0.11
